services:
  caddy:
    build: ./caddy
    pull_policy: build
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - bridge
      - host
  portainer:
    image: portainer/portainer-ce:latest