networks:
  web:
    external: true
  internal:
    external: false
    driver: bridge

services:
  caddy:
    build: ./caddy
    pull_policy: build
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
      - internal
  portainer:
    image: portainer/portainer-ce:latest
    networks:
      - internal